package domain;

public class Room {
	
	private String code;
	private Integer capacity;
	private Boolean hasComputers;
	
	public Room(String code, Integer capacity, Boolean hasComputers) {
		// super(); // Idk what's this line, it was autogenerated
		this.code = code;
		this.capacity = capacity;
		this.hasComputers = hasComputers;
	}
	
	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @return the capacity
	 */
	public Integer getCapacity() {
		return capacity;
	}

	/**
	 * @return true if the room has computers
	 */
	public Boolean hasComputers() {
		return hasComputers;
	}
	
	@Override
	public String toString() {
		return code;
	}
}
